// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhWkQKD-Bjoun_Ar9tWl8uT3hG06bVd5w',
    appId: '1:101431362113:web:e267c2ae1795885c493cc0',
    messagingSenderId: '101431362113',
    projectId: 'flutter-chat-app-cf9ff',
    authDomain: 'flutter-chat-app-cf9ff.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cf9ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACXYhSApAjHhYeAgRm1uoIAa8U2zbWF80',
    appId: '1:101431362113:android:46596a372aa15c76493cc0',
    messagingSenderId: '101431362113',
    projectId: 'flutter-chat-app-cf9ff',
    storageBucket: 'flutter-chat-app-cf9ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw0v4fNuk558i-ctIePRYGxPxuyKYhFTk',
    appId: '1:101431362113:ios:38f5e150da5776ce493cc0',
    messagingSenderId: '101431362113',
    projectId: 'flutter-chat-app-cf9ff',
    storageBucket: 'flutter-chat-app-cf9ff.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw0v4fNuk558i-ctIePRYGxPxuyKYhFTk',
    appId: '1:101431362113:ios:38f5e150da5776ce493cc0',
    messagingSenderId: '101431362113',
    projectId: 'flutter-chat-app-cf9ff',
    storageBucket: 'flutter-chat-app-cf9ff.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhWkQKD-Bjoun_Ar9tWl8uT3hG06bVd5w',
    appId: '1:101431362113:web:cd40e361a66bce5a493cc0',
    messagingSenderId: '101431362113',
    projectId: 'flutter-chat-app-cf9ff',
    authDomain: 'flutter-chat-app-cf9ff.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cf9ff.firebasestorage.app',
  );

}